#!/usr/bin/env bash
# Bash script that will display function_test about commands
function_test(){
	domain="$1"
	subdomain="$2"

dig "$subdomain.$domain" | awk -v subdomain="$2" '/;; ANSWER SECTION:/{getline; print "The subdomain "subdomain" is a " $4 " record and points to " $5}'
}

for subdomain in "www" "lb-01" "web-01" "web-02"
do
	if [ -z "$2" ] || [ "$2" == "$subdomain" ];
	then
		function_test "$1" "$subdomain"
	fi
done
