#!/usr/bin/env bash
# Bash script that will display information about commands

function_test()
{
    if [ -z "$2" ]
    then
        commands=("www" "lb-01" "web-01" "web-02")
    else
        commands=$2
    fi
    for subdomain in "${commands[@]}"
    do
        echo -n "The subdomain $subdomain"
        dig "$subdomain.$1" | grep -A1 'ANSWER SECTION:' | tail -n -1 | awk '{ print " is a " $4 " record and points to " $5}'
    done
}
function_test "$1" "$2"
exit 0
