#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages,

sudo apt-get -y update
sudo apt-get install -y nginx
echo 'Holberton School' >> /var/www/html/index.nginx-debian.html
sudo service nginx start
