#!/usr/bin/env bash
#  Redirection

sudo apt-get update
sudo sed -i "/^\tlocation \// i\ \tlocation /redirect_me {\n\t\treturn 301 https://calypsobronte.me;\n\t}"  /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo service nginx start
