#!/usr/bin/env bash
#  Redirection url

url="\tlocation /redirect_me {\n\t\treturn 301 https://calypsobronte.me/;\n\t}"
file="/etc/nginx/sites-available/default"

sudo sed -i "/server_name {/i $url" "$file"
sudo service nginx restart
