#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages,

sudo apt-get -y update
sudo apt-get install -y nginx
echo 'Holberton School' >> /var/www/html/index.nginx-debian.html
sed -i "/sendfile on;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart