#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages,

sudo apt-get -y update
sudo apt-get install -y nginx
echo 'Holberton School' >> /var/www/html/index.nginx-debian.html
sudo sed -i "/^\tlocation \// i\ \tlocation /redirect_me {\n\t\treturn 301 https://calypsobronte.me;\n\t}" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee -a /usr/share/nginx/html/terror_404.html
sudo sed -i "46i \\\terror_page 404 /terror_404.html;\n\tlocation = /terror_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}" /etc/nginx/sites-enabled/default
sudo sed -i "/sendfile on;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart