#!/usr/bin/env bash
#  Install load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*
echo "frontend localnodes bind *:80 mode http default_backend nodes backend nodes mode http balance roundrobin server 1095-web-01 34.74.228.47:80 server 1095-web-02 100.26.141.181:80" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart